echo GRM_DEFAULT_HOST=$GRM_DEFAULT_HOST
echo GRM_DEFAULT_ORG=$GRM_DEFAULT_ORG
echo GRM_DEFAULT_SCHEME=$GRM_DEFAULT_SCHEME
echo GRM_HOME=$GRM_HOME
echo GRM_SCRIPT=$GRM_SCRIPT
echo GRM_SCRIPT_HOME=$GRM_SCRIPT_HOME
