. shmod

echo GRM_DEFAULT_HOST=$GRM_DEFAULT_HOST
echo GRM_DEFAULT_SCHEME=$GRM_DEFAULT_SCHEME
echo GRM_HOME=$GRM_HOME
echo SCRIPT_HOME=$SCRIPT_HOME
echo SHLN_HOME=$SHLN_HOME
echo SHMOD_HOME=$SHMOD_HOME
